export PATH="/home/ec2-user/minimap2-2.21_x64-linux:$PATH"
export PATH="/home/ec2-user/vartrix_dir:$PATH"
export PATH="/home/ec2-user/souporcell/troublet/target/release:$PATH"
export PATH="/home/ec2-user/souporcell/souporcell/target/release:$PATH"
export PATH="/home/ec2-user/souporcell:$PATH"
export PATH="/home/ec2-user/minimap2-2.21_x64-linux:$PATH"
export PATH="/home/ec2-user/freebayes-v1.3.0:$PATH"